niwanetwork/niwa-website

_api.php
* Adding Pokémon Central discord server
* Adding Wikibound (it) discord server
* Updating Xenopedia telegram chat
=> updating some italian social

cross-wiki-weekend-2020.php
Minor fixes on the Italian version of the guide especially.
=> Updates to Cross-Wiki Weekend IT

cross-wiki-weekend-2020.php
Opening submissions of CWW 2020 contributions.
=> Cross-Wiki Weekend 2020 Submissions Open

cross-wiki-weekend-2020.php
Note: I think "`&#232;`" and "`&egrave;`" are equivalent, the latter is easier to remember, but I'll use the former for the sake of consistency.
=> Update the Italian translation

_menu.php
=> Removing edit-by-pigeon in menu

_api.php, data/members.json, rarticle.php
* Also update some member data
=> Add Interwikis, parameterize urls, separate parameter for Main Page

_footer.php, _header.php, _menu.php, _sidebar.php, members.php, style.css
Keeping those inline CSS styles...in line...by moving them to style.css where they belong.
Also fixed #30 and #46 while I was at it since both are CSS-related. Didn't bother refactoring files that looked like they weren't in use.
=> CSS Refactor + related CSS bug fixes

data/affiliates.json
Add title for Wikimon used on their main page.
=> Adding Wikimon title

data/members.json
Fixed links to Zeldapendium, MarioWiki, and Super Mario WIki (IT)
=> Fixing links

members.php
Updating member links to use the latest API updates.
=> Fix for member logo links

style.css
Removing tweet, search, and hey-listen CSS that is no longer used anywhere.
=> Removing unused CSS

_sidebar.php, style.css
=> Adding Discord widget to sidebar

contact.php, style.css
This PR both fixes a visual bug on the contact page, and refactors the form to use label elements.
=> Use labels for contact form, refactor styling

index.php, style.css
=> Carousel fixes

style.css
=> Section headers

_api.php, index.php
=> Automating homepage member and affiliate count

data/members.json
Previous account has been purged
=> Restore StrategyWiki Twitter name

data/members.json
Changed Fire Emblem Wiki description, because it isn't new or small anymore.
=> Changed Fire Emblem Wiki description

join.php
_Should only be merged after https://github.com/niwanetwork/niwa-docs/pull/1 is merged_
Updating our `join` page with our new member and affiliate admission criteria, pulled from the niwa-docs repo.
=> New member+affiliate criteria

cross-wiki-weekend-2021.php
Congratulations on the spell-check ya'll lol :P
=> Fix sunmarsh name on Cross Wiki Weekend 2021 page

_sidebar.php
It was bugging me that the style and the code was not uniform
=> Added div around the discord-box to add a margin between title and the box (like on the twitter box)

data/members.json
Inkipedia branching off to dedicated discord server
=> Update inkipedia discord

data/members.json
No more Wars Central involvement
=> Update Wars Wiki description

edit-by-pigeon.php
=> Fix Zelda link

cross-wiki-week-2022.php, cross-wiki-week-2023.php
Adding conclusions for Cross-Wiki Week in 2022 + 2023 (n̶e̶v̶e̶r̶ ̶d̶i̶d̶ ̶t̶h̶e̶ ̶2̶0̶2̶2̶ ̶c̶o̶n̶c̶l̶u̶s̶i̶o̶n̶ ̶b̶e̶c̶a̶u̶s̶e̶ ̶i̶t̶ ̶w̶a̶s̶ ̶e̶m̶b̶a̶r̶a̶s̶s̶i̶n̶g).
Will also need Italian translations (that can come later).
=> Adding conclusions for CWW 2022+2023
